### PR TITLE
Fix readlink for os x.

### LINKED ISSUE #104: readlink -f not available on os x
The `realink` provided by os x, doesn't support the `-f` flat of gnu's `readline`. This causes the `build.sh` script to be broken.

### PR DESCRIPTION
**Pull request by angerman**
This should fix #104.

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -1,8 +1,34 @@
...
+# readlink on os x, doesn't support -f, to prevent the
+# need of installing coreutils (e.g. through brew, just
+# for readlink, we use the follownig substitute.
+#
+# source: http://stackoverflow.com/a/1116890
+function rl {
+    TARGET_FILE=$1
+
+    cd "$(dirname "$TARGET_FILE")"
+    TARGET_FILE=$(basename "$TARGET_FILE")
```
Comment (quchen) [inline build.sh]: Quotes around $() missing

File: build.sh [hunk 2]
```diff
@@ -1,8 +1,34 @@
...
+
+    # Iterate down a (possible) chain of symlinks
+    while [ -L "$TARGET_FILE" ]
+    do
+        TARGET_FILE=$(readlink "$TARGET_FILE")
```
Comment (quchen) [inline build.sh]: quotes

File: build.sh [hunk 3]
```diff
@@ -1,8 +1,34 @@
...
+        cd "$(dirname "$TARGET_FILE")"
+        TARGET_FILE=$(basename "$TARGET_FILE")
```
Comment (quchen) [inline build.sh]: quotes

File: build.sh [hunk 4]
```diff
@@ -1,8 +1,34 @@
...
+    done
+
+    # Compute the canonicalized name by finding the physical path 
+    # for the directory we're in and appending the target file.
+    PHYS_DIR=`pwd -P`
```
Comment (quchen) [inline build.sh]: Use `$(xxx)` instead of `` `x` ``

File: build.sh [hunk 5]
```diff
@@ -1,8 +1,34 @@
...
+    RESULT=$PHYS_DIR/$TARGET_FILE
```
Comment (quchen) [inline build.sh]: quotes

File: build.sh [hunk 6]
```diff
@@ -1,8 +1,34 @@
...
+    echo $RESULT
```
Comment (quchen) [inline build.sh]: quotes

File: build.sh [hunk 7]
```diff
@@ -1,8 +1,34 @@
 #!/usr/bin/env bash
 
+# readlink on os x, doesn't support -f, to prevent the
+# need of installing coreutils (e.g. through brew, just
+# for readlink, we use the follownig substitute.
+#
+# source: http://stackoverflow.com/a/1116890
+function rl {
+    TARGET_FILE=$1
```
Comment (quchen) [inline build.sh]: quotes

File: build.sh [hunk 8]
```diff
@@ -1,8 +1,34 @@
...
+    done
+
+    # Compute the canonicalized name by finding the physical path 
+    # for the directory we're in and appending the target file.
+    PHYS_DIR=`pwd -P`
+    RESULT=$PHYS_DIR/$TARGET_FILE
+    echo $RESULT
+}
+
 set -euo pipefail
```
Comment (quchen) [inline build.sh]: This should be the second line after #! so the whole script is affected
